vets:
  cache:
    ttl: 60
    heap-size: 100

---
spring:
  profiles: default
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    # comment out as this configuration conflicts with Azure Spring Cloud
    # instance-id: ${spring.application.name}:${random.uuid}
